site_name: D-EcoImpact documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
          selection:
            inherited_members: false

      custom_templates: templates
repo_url: https://github.com/Deltares/D-EcoImpact
repo_name: deltares/D-EcoImpact
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/deltares/

copyright: |
  Copyright &copy; 2023 <a href="https://www.deltares.nl/en/"  target="_blank" rel="noopener">Deltares</a>
