site_name: D-EcoImpact documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
          selection:
            inherited_members: false
  - print-site

markdown_extensions:
  - attr_list

repo_url: https://github.com/Deltares/D-EcoImpact
repo_name: Deltares/D-EcoImpact
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/deltares/

nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Development: "development.md"
  - User manual:
      - Visualization: "manual/visualization.md"
      - Input files: "manual/input.md"
  - Examples:
      - Volkerak zoommeer: "examples/volkerak.md"
      - Meuse: "examples/maas.md"
  - API reference:
      - Business:
          - "Application.py": "api/business/application.md"
  - Print: "print_page"

copyright: |
  Copyright &copy; 2023 <a href="https://www.deltares.nl/en/"  target="_blank" rel="noopener">Deltares</a>
