[tool.poetry]
name = "decoimpact"
version = "0.1.0"
description = ""
authors = ["Hidde Elzinga <Hidde.Elzinga@Deltares.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
