name: Update Python Poetry packages

on:
  push:
    branches:
      - main
      - '**'

env:
  # The version type to update, based on the commit message (either patch for bug/fix or minor for all other commits)
  VERSION_TYPE: ${{ (startsWith(github.event.head_commit.message, 'Fix') ||
                     startsWith(github.event.head_commit.message, 'fix') ||
                     startsWith(github.event.head_commit.message, 'Bug') ||
                     startsWith(github.event.head_commit.message, 'bug')) &&
                     'patch' || 'minor' }}
  NEW_VERSION: 0

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2
      - name: bump up patch version and update version in template_input.yaml
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry version ${{ env.VERSION_TYPE }}
          PROJECT_VERSION=$(poetry version --short)
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          VERSION_NOTE="version ${{ env.PROJECT_VERSION }}"
          git add pyproject.toml
          sed -i "1 s/.*/${{ VERSION_NOTE }}/" template_input.yaml
          git add template_input.yaml
          git commit -m "bump up ${{ env.VERSION_TYPE }} version from workflow; version = ${{ env.PROJECT_VERSION }}"
          git push
