name: Update Python Poetry packages

on: push
      
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2
      - name: bump up patch version
        run: |
          poetry version ${{ github.event.inputs.version }}
          git add pyproject.toml
          git commit -m "bump up ${{ github.event.inputs.version }} version from workflow"
          git push
