name: Update Python Poetry packages

on: push

env:
  VERSION_TYPE: ${{ startsWith(github.event.head_commit.message, ['Fix', 'fix', 'Bug', 'bug']) == 'refs/heads/main' && 'patch' || 'minor' }}
  
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2
      - name: bump up patch version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry version ${{ VERSION_TYPE }}
          git add pyproject.toml
          git commit -m "bump up ${{ VERSION_TYPE }} version from workflow"
          git push
