name: bump patch version using poetry

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
  push:

env:
  RELEASE_TYPE: patch

jobs:
  bump-up-version:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/version_upgrade.yml
