name: bump patch version using poetry

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
  push:
  workflow_dispatch:

env:
  RELEASE_TYPE: patch

jobs:
  bump-up-version:
    # if: github.event.pull_request.merged == true
    secrets: inherit
    uses: ./.github/workflows/version_upgrade.yml
      env:
        RELEASE_TYPE: ${{ env.RELEASE_TYPE }}
