# This workflow should be triggered when a release of the main is needed.
# It creates a tag and regenerates the documentation to generate a release.
# It does not bump the version number, that happens for the merged pull request.

name: Release major or minor version (create tag and documentation)

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Choose type of release
        default: major
        options:
        - minor
        - major

jobs:
  bump-up-version:
    secrets: inherit
    uses: ./.github/workflows/version_upgrade.yml
    with:
      release_type: ${{ github.event.inputs.release_type }}

  create-release:
    runs-on: ubuntu-latest
    needs: bump-up-version
    steps:
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.bump-up-version.outputs.project_version }}
          release_name: Release ${{ needs.bump-up-version.outputs.project_version }}
          draft: false
          prerelease: false

  create-documentation:
    needs: create-release
    secrets: inherit
    uses: ./.github/workflows/mkdocs_documentation.yml
    with:
      project_version: ${{ needs.bump-up-version.outputs.project_version }}

  docker-build:
    needs: create-release
    uses: ./.github/workflows/docker_image.yml
