# This workflow should be triggered when a release of the main is needed. 
# It creates a tag and regenerates the documentation to generate a release. 
# It does not bump the version number, that happens for the merged pull request.

name: Release major or minor version (create tag and documentation)

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Choose type of release
        default: major
        options:
        - minor
        - major

env:
  RELEASE_TYPE: ${{ github.event.inputs.release_type }}

jobs:
  bump-up-version:
    uses: ./.github/workflows/version_upgrade.yml

  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          release_name: Release ${{ env.PROJECT_VERSION }}
          draft: false
          prerelease: false
      - name: Install Dependencies
        run: poetry install
      - name: Create new version of mkdocs and publish
        run: |
          poetry run mike deploy --push --update-aliases ${PROJECT_VERSION} latest
          poetry run mike set-default --push latest
  
  docker-build:
    uses: ./.github/workflows/docker_image.yml
